version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: weltn24/eb-deployer:latest
    steps:
      - checkout
      - run:
          name: Start Mongo DB
          command: service mongod start
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Npm Test
          command: npm test
workflows:
  version: 2
  status_check:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - production
